### ISSUE TITLE
Selecting Mr. Game and Watch Alt 1 crashes program

### ISSUE THREAD

**Issue by PatrickMiller728** [SSBUTrainingGrounds/GraphicAssembler#1]
Traceback (most recent call last):
  File "D:\Python\Graphics\graphics\ui\views\MainWindow.py", line 64, in <lambda>
    character_dropdown_one.currentTextChanged.connect(lambda: preview.update())
                                                              ^^^^^^^^^^^^^^^^
  File "D:\Python\Graphics\graphics\ui\widgets\ImagePreview.py", line 20, in update
    QPixmap(generate_thumbnail(self.data).toqpixmap()).scaledToHeight(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Graphics\graphics\app\generate.py", line 112, in generate_thumbnail
    canvas.alpha_composite(generate_character_image(character_paths[0]), POSITION[0])
  File "D:\Python\Graphics\venv\Lib\site-packages\PIL\Image.py", line 1783, in alpha_composite
    result = alpha_composite(background, overlay)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Graphics\venv\Lib\site-packages\PIL\Image.py", line 3302, in alpha_composite
    return im1._new(core.alpha_composite(im1.im, im2.im))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: images do not match

I suspect the image format is not correct (RGBA) but not sure

**Comment by PatrickMiller728** [comment]
Yep, just added a line in generate_character_image that converts all character images to RGBA
`character = character.convert("RGBA")`
